export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state"
export ZDOTDIR="$HOME"/.config/zsh
export ANDROID_HOME="$XDG_DATA_HOME"/android
export EDITOR="lvim"
# export BROWSER="microsoft-edge-stable"
export BROWSER="firefox"
export TERM="st"
# export MAIL="mailspring"
export VISUAL="lvim"
export MOZ_USE_XINPUT2=1
export QT_QPA_PLATFORMTHEME="qt6ct"
export GTK2_RC_FILES="$HOME/.gtkrc-2.0"
