# colors

[colors]
[colors.bright]
black = "#7C6F64"
blue = "#7DAEA3"
cyan = "#89B482"
green = "#A9B665"
magenta = "#D3869B"
red = "#EA6962"
white = "#D4BE98"
yellow = "#fabd2f"

[colors.normal]
black = "#1d2021"
blue = "#7DAEA3"
cyan = "#89B482"
green = "#A9B665"
magenta = "#D3869B"
red = "#EA6962"
white = "#A89984"
yellow = "#d79921"

[colors.primary]
background = "#1d2021"
foreground = "#DDC7A1"

# font

[font]
size = 11
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
# normal = { family = "FiraCode Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
# bold = { family = "FiraCode Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
# italic = { family = "FiraCode Nerd Font", style = "Italic" }
