import = [
    "~/dotfiles/.config/alacritty/themes/gruvbox_dark.toml"
]

[font]
size=14.0
# normal = { family = "FiraCode Nerd Font", style = "Retina" }
normal = { family = "JetBrainsMono Nerd Font", style = "Medium" }
# normal = { family = "Dank Mono", style = "Medium" }

[keyboard]
bindings = [
   { key = "Return", mods = "Control|Shift", action = "SpawnNewInstance" }
]

[window]
padding = { x = 5, y = 5 }
opacity=0.97

[mouse]
hide_when_typing = true
